services:
  - type: web
    name: bot-scraper
    env: python
    plan: free
    dockerCommand: python bot/main.py
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: BOLETIN_PALABRAS
        value: "Policia Federal Argentina,Fuerzas de seguridad"
      - key: BOLETIN_NOTIFY_CHAT_ID
        sync: false
      - key: BOT_ADMIN_ID
        sync: false
      - key: PORT
        value: 8000
      - key: MODO
        value: cloud
      - key: CHROME_CDP_URL
        value: http://localhost:9222
      - key: RENDER_EXTERNAL_URL
        value: https://bot-boletin-pfa.onrender.com
